
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdrghqyslcexzeogbdqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkcmdocXlzbGNleHplb2diZHFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NzExOTYsImV4cCI6MjA2MTE0NzE5Nn0.iVsURmj84Ln0CdVuHDiDpmPvYDT4AWowpoprKFPskTQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
